INSERT INTO companies (link_img, id, amount, created, status, updated, category, experience, gender, job_type, location, name, qualification)
VALUES ('/img/svg_icon/1.svg', 1, '$800', now(), 'ACTIVE', now(), 'Java Developer', 'Less 1 year', 'Male', 'Full time', 'Moscow', 'Mother', 'Programmer'),
       ('/img/svg_icon/2.svg', 2, '$850', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Passion', 'Tester'),
       ('/img/svg_icon/3.svg', 3, '$950', now(), 'ACTIVE', now(), 'PHP Developer', 'Less 1 year', 'Female', 'Full time', 'Moscow', 'Smile', 'Programmer'),
       ('/img/svg_icon/4.svg', 4, '$1000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Love', 'Tester'),
       ('/img/svg_icon/5.svg', 5, '$1250', now(), 'ACTIVE', now(), 'Java Developer', 'More 3 years', 'Female', 'Full time', 'Moscow', 'Eternity', 'Programmer'),
       ('/img/svg_icon/1.svg', 6, '$1500', now(), 'ACTIVE', now(), 'Java Developer', 'Less 1 year', 'Male', 'Full time', 'Moscow', 'Fantastic', 'Programmer'),
       ('/img/svg_icon/2.svg', 7, '$2000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Destiny', 'Tester'),
       ('/img/svg_icon/3.svg', 8, '$3000', now(), 'ACTIVE', now(), 'PHP Developer', 'Less 1 year', 'Female', 'Full time', 'Moscow', 'Freedom', 'Programmer'),
       ('/img/svg_icon/4.svg', 9, '$4000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Liberty', 'Tester'),
       ('/img/svg_icon/5.svg', 10, '$5000', now(), 'ACTIVE', now(), 'Java Developer', 'More 3 years', 'Female', 'Full time', 'Moscow', 'Tranquillity', 'Programmer'),
       ('/img/svg_icon/1.svg', 11, '$6000', now(), 'ACTIVE', now(), 'Java Developer', 'Less 1 year', 'Male', 'Full time', 'Moscow', 'Peace', 'Programmer'),
       ('/img/svg_icon/2.svg', 12, '$7000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Blossom', 'Tester'),
       ('/img/svg_icon/3.svg', 13, '$8000', now(), 'ACTIVE', now(), 'PHP Developer', 'Less 1 year', 'Female', 'Full time', 'Moscow', 'Sunshine', 'Programmer'),
       ('/img/svg_icon/4.svg', 14, '$9000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Sweetheart', 'Tester'),
       ('/img/svg_icon/5.svg', 15, '$10000', now(), 'ACTIVE', now(), 'Java Developer', 'More 3 years', 'Female', 'Full time', 'Moscow', 'Gorgeous', 'Programmer'),
       ('/img/svg_icon/1.svg', 16, '$11000', now(), 'ACTIVE', now(), 'Java Developer', 'Less 1 year', 'Male', 'Full time', 'Moscow', 'Cherish', 'Programmer'),
       ('/img/svg_icon/2.svg', 17, '$12000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Enthusiasm', 'Tester'),
       ('/img/svg_icon/3.svg', 18, '$13000', now(), 'ACTIVE', now(), 'PHP Developer', 'Less 1 year', 'Female', 'Full time', 'Moscow', 'Hope', 'Programmer'),
       ('/img/svg_icon/4.svg', 19, '$14000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Grace', 'Tester'),
       ('/img/svg_icon/5.svg', 20, '$15000', now(), 'ACTIVE', now(), 'Java Developer', 'More 3 years', 'Female', 'Full time', 'Moscow', 'Rainbow', 'Programmer'),
       ('/img/svg_icon/1.svg', 21, '$16000', now(), 'ACTIVE', now(), 'Java Developer', 'Less 1 year', 'Male', 'Full time', 'Moscow', 'Blue', 'Programmer'),
       ('/img/svg_icon/2.svg', 22, '$17000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Sunflower', 'Tester'),
       ('/img/svg_icon/3.svg', 23, '$18000', now(), 'ACTIVE', now(), 'PHP Developer', 'Less 1 year', 'Female', 'Full time', 'Moscow', 'Twinkle', 'Programmer'),
       ('/img/svg_icon/4.svg', 24, '$19000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Serendipity', 'Tester'),
       ('/img/svg_icon/5.svg', 25, '$20000', now(), 'ACTIVE', now(), 'Java Developer', 'More 3 years', 'Female', 'Full time', 'Moscow', 'Bliss', 'Programmer'),
       ('/img/svg_icon/1.svg', 26, '$21000', now(), 'ACTIVE', now(), 'Java Developer', 'Less 1 year', 'Male', 'Full time', 'Moscow', 'Lullaby', 'Programmer'),
       ('/img/svg_icon/2.svg', 27, '$22000', now(), 'ACTIVE', now(), 'Python Developer', 'More 1 year', 'Male', 'Part time', 'California', 'Sophisticated', 'Tester'),
       ('/img/svg_icon/3.svg', 28, '$23000', now(), 'ACTIVE', now(), 'PHP Developer', 'Less 1 year'', ''Female'', ''Full time'', ''Moscow'', ''Renaissance'', ''Programmer''),
       (''/img/svg_icon/4.svg'', 29, ''$24000'', now(), ''ACTIVE'', now(), ''Python Developer'', ''More 1 year', 'Male', 'Part time', 'California', 'Cute', 'Tester'),
       ('/img/svg_icon/5.svg', 30, '$24500', now(), 'ACTIVE', now(), 'Java Developer', 'More 3 years', 'Female', 'Full time', 'Moscow', 'Cosy', 'Programmer');

